various fixes
(best commit message ever!)

diff --git a/runall b/runall
--- a/runall
+++ b/runall
@@ -1,1 +1,15 @@
-for a in pages/*; do b=${a/.txt/.rst}; b=pages-step1/${b#pages/}; ./convert.py "$a" > "$b"; done
+#!/bin/bash
+
+errors=0
+
+for a in pages/*; do 
+  b=${a/.txt/.rst}
+  b=pages-step1/${b#pages/}
+  echo -ne "\e[1Gconverting \e[1m$a\e[m\e[K"
+  if ! ./convert.py "$a" > "$b"; then
+    echo -e "Failure at \e[1m$a\e[m"
+    errors=$((errors + 1))
+  fi
+done
+
+echo Errors: $errors
